services:
  wiki-frontend:
    image: wiki-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: wiki-frontend-prod

  wiki-backend:
    image: wiki-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wiki-backend-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf/:ro
    ports:
      - 8080:80
    container_name: wiki-proxy-prod
    depends_on:
      - wiki-frontend
      - wiki-backend